#The Syracuse Sequence is generated by starting with a natural number and repeat-
#edly applying the following function until reaching 1:
#     x/2 (if x is even)
#     3x+1(if x is odd)
#This program gets a starting value from the user and then prints the Syracuse
#sequence in the form of list, for that value.

n=int(input("Enter a starting value: "))
Sequence=[n]
if n%2==0:
    x=n/2
else:
    x=3*n+1
Sequence.append(x)

while True:
        if x%2==0:
             x=x/2
        else:
            x=3*x+1
        Sequence.append(x)
        if x==1:
            break
print(Sequence)
